/** @format */

// Blocklists for Privacy Guardian extension

// Tracker database - known tracking domains
const trackerDatabase = {
  // Common analytics trackers
  "google-analytics.com": { name: "Google Analytics", block: true },
  "analytics.google.com": { name: "Google Analytics", block: true },
  "doubleclick.net": { name: "DoubleClick (Google)", block: true },
  "facebook.net": { name: "Facebook Pixel", block: true },
  "connect.facebook.net": { name: "Facebook Connect", block: true },
  "ads.facebook.com": { name: "Facebook Ads", block: true },
  "pixel.facebook.com": { name: "Facebook Pixel", block: true },
  "analytics.twitter.com": { name: "Twitter Analytics", block: true },
  "ads-twitter.com": { name: "Twitter Ads", block: true },
  "ads-api.twitter.com": { name: "Twitter Ads API", block: true },
  "static.ads-twitter.com": { name: "Twitter Ads Static", block: true },
  "ads-bidder-api.twitter.com": { name: "Twitter Ads Bidder", block: true },
  "advertising.twitter.com": { name: "Twitter Advertising", block: true },
  "sc-static.net": { name: "Snapchat", block: true },
  "hotjar.com": { name: "Hotjar", block: true },
  "mouseflow.com": { name: "Mouseflow", block: true },
  "clarity.ms": { name: "Microsoft Clarity", block: true },

  // Ad networks
  "adnxs.com": { name: "AppNexus", block: true },
  "rubiconproject.com": { name: "Rubicon Project", block: true },
  "pubmatic.com": { name: "PubMatic", block: true },
  "openx.net": { name: "OpenX", block: true },
  "criteo.com": { name: "Criteo", block: true },
  "criteo.net": { name: "Criteo", block: true },
  "taboola.com": { name: "Taboola", block: true },
  "outbrain.com": { name: "Outbrain", block: true },
  "amazon-adsystem.com": { name: "Amazon Ads", block: true },
  "adform.net": { name: "Adform", block: true },
  "adsrvr.org": { name: "The Trade Desk", block: true },
  "advertising.com": { name: "Verizon Media", block: true },
  "adtech.com": { name: "AdTech", block: true },
  "moatads.com": { name: "Moat", block: true },
  "media.net": { name: "Media.net", block: true },
  "smartadserver.com": { name: "Smart AdServer", block: true },
  "casalemedia.com": { name: "Casale Media", block: true },
  "bidswitch.net": { name: "BidSwitch", block: true },
  "sharethrough.com": { name: "Sharethrough", block: true },
  "teads.tv": { name: "Teads", block: true },
  "spotxchange.com": { name: "SpotX", block: true },
  "indexww.com": { name: "Index Exchange", block: true },
  "indexexchange.com": { name: "Index Exchange", block: true },
  "sonobi.com": { name: "Sonobi", block: true },
  "lijit.com": { name: "Sovrn", block: true },
  "sovrn.com": { name: "Sovrn", block: true },
  "gumgum.com": { name: "GumGum", block: true },
  "yieldmo.com": { name: "Yieldmo", block: true },
  "triplelift.com": { name: "TripleLift", block: true },
  "contextweb.com": { name: "PulsePoint", block: true },
  "rhythmone.com": { name: "RhythmOne", block: true },
  "quantserve.com": { name: "Quantcast", block: true },
  "quantcount.com": { name: "Quantcast", block: true },
  "mediamath.com": { name: "MediaMath", block: true },
  "mathtag.com": { name: "MediaMath", block: true },
  "adroll.com": { name: "AdRoll", block: true },
  "turn.com": { name: "Turn", block: true },
  "amung.us": { name: "whos.amung.us", block: true },
  "chartbeat.com": { name: "Chartbeat", block: true },
  "chartbeat.net": { name: "Chartbeat", block: true },
  "pardot.com": { name: "Pardot", block: true },
  "marketo.com": { name: "Marketo", block: true },
  "marketo.net": { name: "Marketo", block: true },
  "hubspot.com": { name: "HubSpot", block: true },
  "omtrdc.net": { name: "Adobe Analytics", block: true },
  "demdex.net": { name: "Adobe Audience Manager", block: true },
  "everesttech.net": { name: "Adobe Media Optimizer", block: true },
  "krxd.net": { name: "Salesforce DMP", block: true },
  "bluekai.com": { name: "Oracle BlueKai", block: true },
  "exelator.com": { name: "Nielsen", block: true },
  "scorecardresearch.com": { name: "ScorecardResearch", block: true },
  "newrelic.com": { name: "New Relic", block: true },
  "optimizely.com": { name: "Optimizely", block: true },
  "segment.com": { name: "Segment", block: true },
  "segment.io": { name: "Segment", block: true },
  "mixpanel.com": { name: "Mixpanel", block: true },
  "amplitude.com": { name: "Amplitude", block: true },
  "kissmetrics.com": { name: "Kissmetrics", block: true },
  "crazyegg.com": { name: "Crazy Egg", block: true },
  "fullstory.com": { name: "FullStory", block: true },
  "inspectlet.com": { name: "Inspectlet", block: true },
  "luckyorange.com": { name: "Lucky Orange", block: true },
  "sessioncam.com": { name: "SessionCam", block: true },
  "clicktale.net": { name: "Clicktale", block: true },
  "pendo.io": { name: "Pendo", block: true },
  "heap.io": { name: "Heap", block: true },
  "loggly.com": { name: "Loggly", block: true },
  "bugsnag.com": { name: "Bugsnag", block: true },
  "sentry.io": { name: "Sentry", block: true },
  "rollbar.com": { name: "Rollbar", block: true },
  "appdynamics.com": { name: "AppDynamics", block: true },
  "dynatrace.com": { name: "Dynatrace", block: true },
  "pingdom.net": { name: "Pingdom", block: true },
  "statcounter.com": { name: "StatCounter", block: true },
  "alexa.com": { name: "Alexa", block: true },
  "alexametrics.com": { name: "Alexa Metrics", block: true },
  "addthis.com": { name: "AddThis", block: true },
  "sharethis.com": { name: "ShareThis", block: true },
  "sumome.com": { name: "SumoMe", block: true },
  "sumo.com": { name: "Sumo", block: true },
  "disqus.com": { name: "Disqus", block: true },
  "livefyre.com": { name: "Livefyre", block: true },
  "zopim.com": { name: "Zopim", block: true },
  "zendesk.com": { name: "Zendesk", block: true },
  "intercom.io": { name: "Intercom", block: true },
  "intercom.com": { name: "Intercom", block: true },
  "drift.com": { name: "Drift", block: true },
  "olark.com": { name: "Olark", block: true },
  "tawk.to": { name: "Tawk.to", block: true },
  "livechatinc.com": { name: "LiveChat", block: true },
  "purechat.com": { name: "PureChat", block: true },
  "snapengage.com": { name: "SnapEngage", block: true },
  "boldchat.com": { name: "BoldChat", block: true },
  "uservoice.com": { name: "UserVoice", block: true },
  "freshdesk.com": { name: "Freshdesk", block: true },
  "helpscout.net": { name: "Help Scout", block: true },
  "getsatisfaction.com": { name: "Get Satisfaction", block: true },
  "usabilla.com": { name: "Usabilla", block: true },
  "qualaroo.com": { name: "Qualaroo", block: true },
  "survicate.com": { name: "Survicate", block: true },
  "surveymonkey.com": { name: "SurveyMonkey", block: true },
  "typeform.com": { name: "Typeform", block: true },
  "wufoo.com": { name: "Wufoo", block: true },
  "formstack.com": { name: "Formstack", block: true },
};

// Malicious URL database - known malicious domains
const maliciousDatabase = {
  // Phishing domains
  "secure-paypal.com": {
    name: "PayPal Phishing",
    category: "phishing",
    block: true,
  },
  "paypal-secure.com": {
    name: "PayPal Phishing",
    category: "phishing",
    block: true,
  },
  "account-google.com": {
    name: "Google Phishing",
    category: "phishing",
    block: true,
  },
  "accounts-google.com": {
    name: "Google Phishing",
    category: "phishing",
    block: true,
  },
  "facebook-security.com": {
    name: "Facebook Phishing",
    category: "phishing",
    block: true,
  },
  "apple-icloud.com": {
    name: "Apple Phishing",
    category: "phishing",
    block: true,
  },
  "microsoft-update.com": {
    name: "Microsoft Phishing",
    category: "phishing",
    block: true,
  },
  "verify-twitter.com": {
    name: "Twitter Phishing",
    category: "phishing",
    block: true,
  },

  // Malware domains
  "download-free-movies.com": {
    name: "Malware Distribution",
    category: "malware",
    block: true,
  },
  "getfreesoft.net": {
    name: "Malware Distribution",
    category: "malware",
    block: true,
  },
  "crackfulldownload.com": {
    name: "Malware Distribution",
    category: "malware",
    block: true,
  },
  "piratecracks.com": {
    name: "Malware Distribution",
    category: "malware",
    block: true,
  },
  "fullversiondownload.net": {
    name: "Malware Distribution",
    category: "malware",
    block: true,
  },

  // Scam domains
  "you-won-a-prize.com": { name: "Prize Scam", category: "scam", block: true },
  "claim-your-iphone.com": {
    name: "Prize Scam",
    category: "scam",
    block: true,
  },
  "free-iphone-winner.com": {
    name: "Prize Scam",
    category: "scam",
    block: true,
  },
  "lottery-winner-claim.com": {
    name: "Lottery Scam",
    category: "scam",
    block: true,
  },
  "nigerian-prince-fund.com": {
    name: "Advance Fee Scam",
    category: "scam",
    block: true,
  },
};

// Export the databases
export { trackerDatabase, maliciousDatabase };
